# Generated by Django 3.2.3 on 2021-05-22 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='post_id',
            new_name='object_id',
        ),
    ]
