# Generated by Django 3.2.3 on 2021-05-23 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_alter_likeanalytics_liked_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likeanalytics',
            name='liked_time',
            field=models.DateField(auto_now=True),
        ),
    ]
