# Generated by Django 3.2.3 on 2021-05-23 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_auto_20210523_2039'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_login',
            field=models.DateField(blank=True, null=True),
        ),
    ]
