# Generated by Django 3.2.3 on 2021-05-23 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_alter_profile_last_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='last_request',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
